# Custom Chatbot Project

The dataset I have chosen is the **character_descritpions** dataset provided in .csv file. This dataset is suitable for the task because it provides specific information about some characters which a general LLM model does not have. So it's easy to compare the answer before/after providing necessary context.

## Data Wrangling

TODO: In the cells below, load your chosen dataset into a `pandas` dataframe with a column named `"text"`. This column should contain all of your text data, separated into at least 20 rows.

In [1]:
import openai
openai.api_base = "https://openai.vocareum.com/v1"
openai.api_key = "YOUR API KEY"

Load dataset into Pandas DataFrame

In [2]:
import pandas as pd
import requests

df = pd.DataFrame()
df_origin = pd.read_csv("./data/character_descriptions.csv")
df["text"] = df_origin[["Name", "Medium", "Setting", "Description"]].agg(' - '.join, axis=1)
df["text"]

0     Emily - Play - England - A young woman in her ...
1     Jack - Play - England - A middle-aged man in h...
2     Alice - Play - England - A woman in her late 3...
3     Tom - Play - England - A man in his 50s, Tom i...
4     Sarah - Play - England - A woman in her mid-20...
5     George - Play - England - A man in his early 3...
6     Rachel - Play - England - A woman in her late ...
7     John - Play - England - A man in his 60s, John...
8     Maria - Movie - Texas - A middle-aged Latina w...
9     Caleb - Movie - Texas - A young African Americ...
10    Tyler - Movie - Texas - A white man in his mid...
11    Sonya - Movie - Texas - A white woman in her l...
12    Manuel - Movie - Texas - A middle-aged Hispani...
13    Will - Movie - Texas - A white man in his earl...
14    Mia - Limited Series - Australia - A young Aus...
15    Lucas - Limited Series - Australia - A middle-...
16    Tahlia - Limited Series - Australia - A young ...
17    Max - Limited Series - Australia - A white Aus...
18    Ava - Limited Series - Australia - A middle-ag...
19    Donna - Musical - USA - A seasoned performer w...
20    Johnny - Musical - USA - A young up-and-coming...
21    Sable - Musical - USA - A sultry and dramatic ...
22    Dolly - Musical - USA - A bubbly and vivacious...
23    Vixen - Musical - USA - A fierce and competiti...
24    Karma - Musical - USA - A chameleon-like perfo...
25    Crystal - Musical - USA - A quirky and imagina...
26    Olivia - Reality Show - USA - A confident and ...
27    Marcus - Reality Show - USA - A charming and s...
28    Maya - Reality Show - USA - A kind and compass...
29    James - Reality Show - USA - A handsome and at...
30    Sophia - Reality Show - USA - A fun-loving and...
31    Noah - Reality Show - USA - A quirky and creat...
32    Chloe - Reality Show - USA - A driven and ambi...
33    Jake - Reality Show - USA - A laid-back and ea...
34    Prince Lorenzo - Opera - Italy - A charming an...
35    Signora Rosa - Opera - Italy - A mysterious an...
36    Baron Gustavo - Opera - Italy - A wealthy and ...
37    Francesca - Opera - Italy - A fiery and passio...
38    Don Carlo - Opera - Italy - A charming and cha...
39    Duke Orsino - Play - Ancient Greece - A pompou...
40    Lady Olivia - Play - Ancient Greece - A wealth...
41    Sir Toby Belch - Play - Ancient Greece - A dru...
42    Malvolio - Play - Ancient Greece - A pompous a...
43    Viola - Play - Ancient Greece - A plucky and r...
44    Sir Andrew Aguecheek - Play - Ancient Greece -...
45    Bianca - Play - Ancient Greece - Lady Olivia's...
46    Sebastian - Play - Ancient Greece - Viola's tw...
47    Feste - Play - Ancient Greece - A jester and m...
48    Antonio - Play - Ancient Greece - A sea captai...
49    Abigail - Sitcom - USA - A plucky and resource...
50    Thomas - Sitcom - USA - A good-natured and aff...
51    Reverend Brown - Sitcom - USA - The pious and ...
52    Captain James - Sitcom - USA - The charismatic...
53    Mrs. Mercer - Sitcom - USA - The matriarch of ...
54    Mr. Mercer - Sitcom - USA - The bumbling and a...
Name: text, dtype: object

Create embeddings for each text

In [3]:
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
batch_size = 10
embeddings = []
for i in range(0, len(df), batch_size):
    # Send text data to OpenAI model to get embeddings
    response = openai.Embedding.create(
        input=df.iloc[i:i+batch_size]["text"].tolist(),
        engine=EMBEDDING_MODEL_NAME
    )
    
    # Add embeddings to list
    embeddings.extend([data["embedding"] for data in response["data"]])

# Add embeddings list to dataframe
df["embeddings"] = embeddings
df

,text,embeddings
0,Emily - Play - England - A young woman in her ...,"[-0.01285545527935028, -0.011429925449192524, ..."
1,Jack - Play - England - A middle-aged man in h...,"[0.011086059734225273, -0.02076270990073681, 0..."
2,Alice - Play - England - A woman in her late 3...,"[0.009414365515112877, -0.007939904928207397, ..."
3,"Tom - Play - England - A man in his 50s, Tom i...","[0.021002890542149544, -0.014546399004757404, ..."
4,Sarah - Play - England - A woman in her mid-20...,"[-0.0065544648095965385, -0.02564818598330021,..."
5,George - Play - England - A man in his early 3...,"[-0.01701248623430729, -0.011330811306834221, ..."
6,Rachel - Play - England - A woman in her late ...,"[-0.00021242130605969578, -0.00926116947084665..."
7,"John - Play - England - A man in his 60s, John...","[0.022466149181127548, -0.013257226906716824, ..."
8,Maria - Movie - Texas - A middle-aged Latina w...,"[-0.013499060645699501, -0.02056492306292057, ..."
9,Caleb - Movie - Texas - A young African Americ...,"[0.0057533192448318005, -0.03238619118928909, ..."
10,Tyler - Movie - Texas - A white man in his mid...,"[0.009043212980031967, -0.05019113048911095, -..."
11,Sonya - Movie - Texas - A white woman in her l...,"[0.002856249688193202, -0.029582936316728592, ..."
12,Manuel - Movie - Texas - A middle-aged Hispani...,"[-0.01319692563265562, -0.023992009460926056, ..."
13,Will - Movie - Texas - A white man in his earl...,"[-0.004177689086645842, -0.0389830581843853, 0..."
14,Mia - Limited Series - Australia - A young Aus...,"[-0.009059928357601166, -0.02615550346672535, ..."
15,Lucas - Limited Series - Australia - A middle-...,"[0.003710605204105377, -0.021162249147892, -0...."
16,Tahlia - Limited Series - Australia - A young ...,"[-0.010859623551368713, -0.01836983487010002, ..."
17,Max - Limited Series - Australia - A white Aus...,"[0.0035445080138742924, -0.037146177142858505,..."
18,Ava - Limited Series - Australia - A middle-ag...,"[0.003995570819824934, -0.01570305787026882, -..."
19,Donna - Musical - USA - A seasoned performer w...,"[-0.02970522828400135, -0.017362914979457855, ..."
20,Johnny - Musical - USA - A young up-and-coming...,"[-0.030273685231804848, -0.027213161811232567,..."
21,Sable - Musical - USA - A sultry and dramatic ...,"[-0.026684721931815147, -0.019049113616347313,..."
22,Dolly - Musical - USA - A bubbly and vivacious...,"[-0.03602328523993492, -0.02248859964311123, 0..."
23,Vixen - Musical - USA - A fierce and competiti...,"[-0.033450137823820114, -0.026680782437324524,..."
24,Karma - Musical - USA - A chameleon-like perfo...,"[-0.0026651083026081324, -0.019207047298550606..."
25,Crystal - Musical - USA - A quirky and imagina...,"[-0.005558015778660774, -0.010660722851753235,..."
26,Olivia - Reality Show - USA - A confident and ...,"[-0.00898451916873455, -0.01659996807575226, -..."
27,Marcus - Reality Show - USA - A charming and s...,"[-0.007603941019624472, -0.03845309093594551, ..."
28,Maya - Reality Show - USA - A kind and compass...,"[-0.025801368057727814, -0.02521798573434353, ..."
29,James - Reality Show - USA - A handsome and at...,"[-0.02293379046022892, -0.011335845105350018, ..."
30,Sophia - Reality Show - USA - A fun-loving and...,"[0.014194605872035027, -0.020023822784423828, ..."
31,Noah - Reality Show - USA - A quirky and creat...,"[-0.015962079167366028, -0.02381601184606552, ..."
32,Chloe - Reality Show - USA - A driven and ambi...,"[-0.007601413410156965, -0.011957353912293911,..."
33,Jake - Reality Show - USA - A laid-back and ea...,"[-0.01313567440956831, -0.025126829743385315, ..."
34,Prince Lorenzo - Opera - Italy - A charming an...,"[-0.003481590887531638, -0.020792203024029732,..."
35,Signora Rosa - Opera - Italy - A mysterious an...,"[0.008508950471878052, -0.014070739038288593, ..."
36,Baron Gustavo - Opera - Italy - A wealthy and ...,"[-0.018956676125526428, -0.021309828385710716,..."
37,Francesca - Opera - Italy - A fiery and passio...,"[-0.012934047728776932, -0.02277669869363308, ..."
38,Don Carlo - Opera - Italy - A charming and cha...,"[-0.011052528396248817, -0.011743311770260334,..."
39,Duke Orsino - Play - Ancient Greece - A pompou...,"[-0.005110044497996569, -0.04205935075879097, ..."
40,Lady Olivia - Play - Ancient Greece - A wealth...,"[-0.018771572038531303, -0.022245867177844048,..."
41,Sir Toby Belch - Play - Ancient Greece - A dru...,"[0.0002565037284512073, -0.032443463802337646,..."
42,Malvolio - Play - Ancient Greece - A pompous a...,"[-0.01152096502482891, -0.0331050343811512, -0..."
43,Viola - Play - Ancient Greece - A plucky and r...,"[-0.007627623155713081, -0.040912382304668427,..."
44,Sir Andrew Aguecheek - Play - Ancient Greece -...,"[-0.023481110110878944, -0.02731286734342575, ..."
45,Bianca - Play - Ancient Greece - Lady Olivia's...,"[-0.016001639887690544, -0.023787278681993484,..."
46,Sebastian - Play - Ancient Greece - Viola's tw...,"[-0.008052151650190353, -0.03463263064622879, ..."
47,Feste - Play - Ancient Greece - A jester and m...,"[-0.007394944783300161, -0.0194945577532053, 0..."
48,Antonio - Play - Ancient Greece - A sea captai...,"[-0.002243948634713888, -0.03425215557217598, ..."
49,Abigail - Sitcom - USA - A plucky and resource...,"[-0.02414015121757984, -0.026779059320688248, ..."
50,Thomas - Sitcom - USA - A good-natured and aff...,"[-0.01135946810245514, -0.011255964636802673, ..."
51,Reverend Brown - Sitcom - USA - The pious and ...,"[0.00206200173124671, -0.03361256793141365, 0...."
52,Captain James - Sitcom - USA - The charismatic...,"[-0.0053047058172523975, -0.02263866923749447,..."
53,Mrs. Mercer - Sitcom - USA - The matriarch of ...,"[-0.013759942725300789, -0.014024303294718266,..."
54,Mr. Mercer - Sitcom - USA - The bumbling and a...,"[-0.0022479346953332424, -0.01614895649254322,..."

## Custom Query Completion

TODO: In the cells below, compose a custom query using your chosen dataset and retrieve results from an OpenAI `Completion` model. You may copy and paste any useful code from the course materials.

In [5]:
from openai.embeddings_utils import get_embedding, distances_from_embeddings

def get_rows_sorted_by_relevance(question, df):
    """
    Function that takes in a question string and a dataframe containing
    rows of text and associated embeddings, and returns that dataframe
    sorted from least to most relevant for that question
    """
    
    # Get embeddings for the question text
    question_embeddings = get_embedding(question, engine=EMBEDDING_MODEL_NAME)
    
    # Make a copy of the dataframe and add a "distances" column containing
    # the cosine distances between each row's embeddings and the
    # embeddings of the question
    df_copy = df.copy()
    df_copy["distances"] = distances_from_embeddings(
        question_embeddings,
        df_copy["embeddings"].values,
        distance_metric="cosine"
    )
    
    # Sort the copied dataframe by the distances and return it
    # (shorter distance = more relevant so we sort in ascending order)
    df_copy.sort_values("distances", ascending=True, inplace=True)
    return df_copy

In [6]:
import tiktoken

def create_prompt(question, df, max_token_count):
    """
    Given a question and a dataframe containing rows of text and their
    embeddings, return a text prompt to send to a Completion model
    """
    # Create a tokenizer that is designed to align with our embeddings
    tokenizer = tiktoken.get_encoding("cl100k_base")
    
    # Count the number of tokens in the prompt template and question
    prompt_template = """
    Answer the question based on the context below, and if the question
    can't be answered based on the context, say "I don't know"

    Context: 

    {}

    ---

    Question: {}
    Answer:"""
    
    current_token_count = len(tokenizer.encode(prompt_template)) + \
                            len(tokenizer.encode(question))
    
    context = []
    for text in get_rows_sorted_by_relevance(question, df)["text"].values:
        
        # Increase the counter based on the number of tokens in this row
        text_token_count = len(tokenizer.encode(text))
        current_token_count += text_token_count
        
        # Add the row of text to the list if we haven't exceeded the max
        if current_token_count <= max_token_count:
            context.append(text)
        else:
            break

    return prompt_template.format("\n\n###\n\n".join(context), question)

In [7]:
COMPLETION_MODEL_NAME = "gpt-3.5-turbo-instruct"

def answer_question(
    question, df, max_prompt_tokens=1800, max_answer_tokens=150
):
    """
    Given a question, a dataframe containing rows of text, and a maximum
    number of desired tokens in the prompt and response, return the
    answer to the question according to an OpenAI Completion model
    
    If the model produces an error, return an empty string
    """
    
    prompt = create_prompt(question, df, max_prompt_tokens)
    
    try:
        response = openai.Completion.create(
            model=COMPLETION_MODEL_NAME,
            prompt=prompt,
            max_tokens=max_answer_tokens
        )
        return response["choices"][0]["text"].strip()
    except Exception as e:
        print(e)
        return ""

In [11]:
test_prompt = """
Question: "Who is Soifa's mother and where is she from?"
Answer:
"""

answer_question(test_prompt, df, max_prompt_tokens=1800, max_answer_tokens=150)

"Maria is Soifa's mother and she is from Texas."

## Custom Performance Demonstration

TODO: In the cells below, demonstrate the performance of your custom query using at least 2 questions. For each question, show the answer from a basic `Completion` model query as well as the answer from your custom query.

### Question 1
Who is always worrying her children? How many children does she have?

In [12]:
Q1_prompt = """
Question: "Who is always worrying her children? How many children does she have?"
Answer:
"""

Q1_initial_answer = openai.Completion.create(
    model="gpt-3.5-turbo-instruct",
    prompt=Q1_prompt,
    max_tokens=150
)["choices"][0]["text"].strip()
print("Q1 inital answer:\n{}".format(Q1_initial_answer))

Q1 inital answer:
I'm sorry, I cannot answer this question as it is not specified who "she" refers to in the question. Please provide more context or information.

In [13]:
Q1_custom_answer = answer_question(Q1_prompt, df, max_prompt_tokens=1800, max_answer_tokens=150)
print("Q1 custom answer:\n{}".format(Q1_custom_answer))

Q1 custom answer:
Alice is always worrying about her children and she has two children, including Emily.

### Question 2
What do Ava's husband do?

In [14]:
Q2_prompt = """
Question: "What do Ava's husband do?"
Answer:
"""

Q2_initial_answer = openai.Completion.create(
    model="gpt-3.5-turbo-instruct",
    prompt=Q2_prompt,
    max_tokens=150
)["choices"][0]["text"].strip()
print("Q2 initial answer:\n{}".format(Q2_initial_answer))

Q2 initial answer:
There is not enough information provided in the question to accurately determine what Ava's husband does. We would need more context or information to answer this question accurately.

In [15]:
Q2_custom_answer = answer_question(Q2_prompt, df, max_prompt_tokens=1800, max_answer_tokens=150)
print("Q2 custom answer:\n{}".format(Q2_custom_answer))

Q2 custom answer:
Based on the given information, Ava's husband Lucas is successful businessman and CEO of a major tech company. However, their marriage is on the rocks due to his infidelity.